### ISSUE TITLE
Can't parse rdf+xml in WebID authentication

### ISSUE THREAD

**Issue by reederz** [read-write-web/rww-play#127]
Could not authenticate user with TLS cert:rww.ldp.ParserException: WebClient for https://id.data.fm/reederz -> ContentType=[Some(application/rdf+xml)] -> Can't parse body as an RDF graph
Body=
###### ##########################BODY_BEGIN

<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <ns1:PersonalProfileDocument xmlns:ns1="http://xmlns.com/foaf/0.1/"
     rdf:about="">
    <ns1:primaryTopic rdf:resource="#"/>
  /ns1:PersonalProfileDocument
  <ns2:Person xmlns:ns2="http://xmlns.com/foaf/0.1/"
     rdf:about="#">
    <ns3:key xmlns:ns3="http://www.w3.org/ns/auth/cert#">
      ns3:RSAPublicKey
        <ns3:exponent rdf:datatype="http://www.w3.org/2001/XMLSchema#int">65537/ns3:exponent
        <ns3:modulus rdf:datatype="http://www.w3.org/2001/XMLSchema#hexBinary">BCD1E427D1572C508BAB9E13A8176C70BD36DEF9A61E470BD3E1352BA166EB6BB835599569F1C4CB1435E99D60BE6F785E17B5B17DBE7FC7F48C1622179F07A563B6343AA3D0E2EFCAC7EA0F73B9595922152687DADAF696F160A2FF060D75248E69265610C33403B8C90A4F99D5EB3876F60CD2617073A751EEF28F78DE0659249CA9DCFAAFDC805874AEE106E2DD7D60EFFE1820E46308F291CB0BEAD9C7554C100037A739E4EE686AAF8A43B1FA269D6002347F906D5A02279238DB89F29BD257EFFCDA64BC2C3D8378F086FD6B5391F78FDABEE1D4A3974377A5380DB04CC9DFD3CD6877D44CC244EBF0076512A673A71408122749175648EAB60CCAA415/ns3:modulus
      /ns3:RSAPublicKey
    /ns3:key
    <ns2:mbox rdf:resource="mailto:justas.azna@gmail.com"/>
    ns2:nameJustas Azna/ns2:name
  /ns2:Person
/rdf:RDF
###### ##########################BODY_END

```
at rww.ldp.WSClient$$anonfun$fetch$1.apply(WebClient.scala:108)
at rww.ldp.WSClient$$anonfun$fetch$1.apply(WebClient.scala:89)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Caused by: rww.ldp.ParserException: Can't parse https://id.data.fm/reederz with any mime types of Set(MimeType(application,rdf+xml,Map())). Original contentType was Some(application/rdf+xml)
    at rww.ldp.WSClient$$anonfun$rww$ldp$WSClient$$tryToReadAsGraph$1.applyOrElse(WebClient.scala:134)
    at rww.ldp.WSClient$$anonfun$rww$ldp$WSClient$$tryToReadAsGraph$1.applyOrElse(WebClient.scala:134)
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
    at scala.util.Failure.recoverWith(Try.scala:172)
    at rww.ldp.WSClient.rww$ldp$WSClient$$tryToReadAsGraph(WebClient.scala:134)
    at rww.ldp.WSClient$$anonfun$fetch$1.apply(WebClient.scala:95)
    ... 16 more
Caused by: rww.ldp.MissingParserException: no RDF Reader found for mime type MimeType(application,rdf+xml,Map()) for reading https://id.data.fm/reederz
    at rww.ldp.WSClient.rww$ldp$WSClient$$readGraph(WebClient.scala:173)
    at rww.ldp.WSClient$$anonfun$3$$anonfun$apply$2.applyOrElse(WebClient.scala:179)
    at rww.ldp.WSClient$$anonfun$3$$anonfun$apply$2.applyOrElse(WebClient.scala:179)
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
    at scala.util.Failure.recoverWith(Try.scala:172)
    at rww.ldp.WSClient$$anonfun$3.apply(WebClient.scala:179)
    at rww.ldp.WSClient$$anonfun$3.apply(WebClient.scala:179)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
    at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
    at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:105)
    at rww.ldp.WSClient.tryToReadWithMimeTypes(WebClient.scala:182)
    ... 18 more

**Comment by bblfish** [comment]
thanks

**Comment by bblfish** [comment]
This is now fixed in latest commit.
