### ISSUE TITLE
Timeout error on localhost https

### ISSUE THREAD

**Issue by peacekeeper** [read-write-web/rww-play#147]
If I start as follows:

```
./activator run -Dhttps.port=9001 -Dhttps.trustStore=noCA -Dakka.loglevel=DEBUG -Dakka.debug.receive=on -Drww.root.container.path=test_www -Dhttp.hostname=freedom.box 
```

And then I go to https://127.0.0.1:9001, I get this error:

```
Ask timed out on [Actor[akka://rww/user/router#-387609008]] after [30000 ms]
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://rww/user/router#-387609008]] after [30000 ms]
        at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
        at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
        at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by almereyda** [comment]
I am getting the same error when using the `Dockerfile` from @michielbdejong 

```
curl -k https://5.9.161.179:443/2013/card
Ask timed out on [Actor[akka://rww/user/router#-597804069]] after [30000 ms]
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://rww/user/router#-597804069]] after [30000 ms]
        at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
        at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
        at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
        at java.lang.Thread.run(Thread.java:745)
```

which also appears in the containers log. Despite that, the container uses heavy 620 MiB in RAM, but that may be okay for a Java application.

**Comment by reederz** [comment]
When starting the server, you can provide -Dhttp.hostname flag (defaults to localhost). Then, you must have the same host added to your /etc/hosts file (or DNS configured). Unfortunately, requesting directly via ip address, will always give the aforementioned error.

Also see https://github.com/read-write-web/rww-play/issues/152
