### ISSUE TITLE
Stacktrace printed in the browser about WebId auth

### ISSUE THREAD

**Issue by slorber** [read-write-web/rww-play#38]
When trying to visit https://localhost:8443/2013/card with my browser, it printed (in the browser, not in logs) the following stacktrace

```
null
rww.ldp.auth.WebIDVerificationFailure
    at rww.ldp.auth.WebIDVerifier$$anonfun$verifyWebID$1$$anonfun$5.apply(WebIDVerifier.scala:165)
    at rww.ldp.auth.WebIDVerifier$$anonfun$verifyWebID$1$$anonfun$5.apply(WebIDVerifier.scala:154)
    at scala.Option.getOrElse(Option.scala:120)
    at rww.ldp.auth.WebIDVerifier$$anonfun$verifyWebID$1.apply(WebIDVerifier.scala:154)
    at rww.ldp.auth.WebIDVerifier$$anonfun$verifyWebID$1.apply(WebIDVerifier.scala:140)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by slorber** [comment]
btw at the beginning it starts by saying "no access for read on /2013/card" and then after refresh there's the stacktrace

I have not installed any certificate in my browser, but I find it strange to have 2 distinct errors
