### ISSUE TITLE
A client authentication on https with a certificate that fails to verify does not fail correctly.

### ISSUE THREAD

**Issue by bblfish** [read-write-web/rww-play#42]
I have a certificate that contains a webid `http://webid-demo.openspring.net/user/28c` that returns HTML which we perhaps don't interpret correctly at present. The error
currently is a `417 Expectation Failed` with the following message:

```
no Iteratee/parser for Content-Type Some(text/html; charset=utf-8) fetching http://webid-demo.openspring.net/user/28
rww.ldp.LocalException: no Iteratee/parser for Content-Type Some(text/html; charset=utf-8) fetching http://webid-demo.openspring.net/user/28
    at rww.ldp.WSClient$$anonfun$fetch$1.apply(WebClient.scala:103)
    at rww.ldp.WSClient$$anonfun$fetch$1.apply(WebClient.scala:82)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

One could return a  [401 Unauthorized](https://tools.ietf.org/html/rfc2616#section-10.4.2) but that would require returning Basic-Auth header.

In a future better implementation of TLS it would be good to be able to send a message directly to the TLS layer so that it does not accept the certificate if it cannot be verified.

**Comment by bblfish** [comment]
fixed by:
- commit 326ba70f002dbed2f3714e91e1e317122d9d6d99 "minor improvement in Scala match statement"
- commit 8cea89d801b0657c2c9ba8ba5db8968754d46dc3 "improved HTTP error messages ExpectationFailed => InternalServerError"
- commit 0397f06d0a3dfffb1bde70481cc857184ef35bd7: "return 401 when can't authenticate using x509 cert - arguable"

So now it returns `401 Unauthorized` with the content below. The content evidently should be RDFized to make
it useful to clients.

``` java
Could not authenticate user with TLS cert:rww.ldp.WrappedException: failure fetching resource
    at rww.ldp.LDPWebActor$$anonfun$runCmd$6.apply(LDPWebActor.scala:155)
    at rww.ldp.LDPWebActor$$anonfun$runCmd$6.apply(LDPWebActor.scala:146)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
