### ISSUE TITLE
Can't GET the /2013/card anymore

### ISSUE THREAD

**Issue by slorber** [read-write-web/rww-play#57]
sebastien@sebastien-xps:rww-play (master *+%)$ curl -i -k --cert eg/test-localhost.pem:test https://localhost:8443/2013/card -H "ContentType: text/turtle"
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Content-Length: 842

scalax.io.ScalaIOException cannot be cast to scala.Option
java.lang.ClassCastException: scalax.io.ScalaIOException cannot be cast to scala.Option
    at rww.ldp.auth.WACAuthZ$$anon$1$$anonfun$apply$3.apply(WACAuthZ.scala:81)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by bblfish** [comment]
Can't duplicate the problem. Something else must be missing....

**Comment by slorber** [comment]
This happens because of a bad ttl on the hard drive.

The exception is:

```
[INFO] [12/02/2013 17:56:57.276] [rww-akka.actor.default-dispatcher-4] [akka://rww/user/rootContainer/card] in PlantainLDPRActor.runLocalCmd - received GetMeta(https://localhost:8443/2013/card,<function1>)
MainException: class org.openrdf.rio.RDFParseException(Expected '.', found '<' [line 24])
    org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:691)
    org.openrdf.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1208)
    org.openrdf.rio.turtle.TurtleParser.verifyCharacterOrFail(TurtleParser.java:1089)
    org.openrdf.rio.turtle.TurtleParser.parseStatement(TurtleParser.java:246)
    org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:201)
    org.w3.banana.plantain.PlantainTurtleReader$$anonfun$read$1$$anonfun$apply$1.apply(PlantainRDFReader.scala:36)
    org.w3.banana.plantain.PlantainTurtleReader$$anonfun$read$1$$anonfun$apply$1.apply(PlantainRDFReader.scala:32)
    scalax.io.Resource$class.liftedTree1$1(Resource.scala:192)
    scalax.io.Resource$class.acquireFor(Resource.scala:192)
    scalax.io.managed.ReaderResource.acquireFor(ReaderResource.scala:9)
    resource.ManagedResourceOperations$class.acquireAndGet(ManagedResourceOperations.scala:25)
    scalax.io.managed.ReaderResource.acquireAndGet(ReaderResource.scala:9)
    org.w3.banana.plantain.PlantainTurtleReader$$anonfun$read$1.apply(PlantainRDFReader.scala:32)
    org.w3.banana.plantain.PlantainTurtleReader$$anonfun$read$1.apply(PlantainRDFReader.scala:32)
    scala.util.Try$.apply(Try.scala:161)
    org.w3.banana.plantain.PlantainTurtleReader$.read(PlantainRDFReader.scala:31)
    org.w3.banana.RDFReader$class.read(RDFReader.scala:20)
    org.w3.banana.plantain.PlantainTurtleReader$.read(PlantainRDFReader.scala:27)
    rww.ldp.PlantainLDPRActor$$anon$1.load(PlantainLDPRActor.scala:52)
    rww.ldp.PlantainLDPRActor$$anon$1.load(PlantainLDPRActor.scala:41)
    com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
    com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
    com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
    com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
    com.google.common.cache.LocalCache.get(LocalCache.java:3932)
    com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
    com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
    rww.ldp.PlantainLDPRActor.getResource(PlantainLDPRActor.scala:97)
    rww.ldp.PlantainLDPRActor.runLocalCmd(PlantainLDPRActor.scala:165)
    rww.ldp.PlantainLDPRActor.adviceCmd(PlantainLDPRActor.scala:279)
    rww.ldp.PlantainLDPRActor$$anonfun$receive$1.applyOrElse(PlantainLDPRActor.scala:289)
    scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
    scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
    scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
    rww.ldp.RActor$$anon$1.apply(LDPStore.scala:31)
    rww.ldp.RActor$$anon$1.apply(LDPStore.scala:25)
    scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
    rww.ldp.RActor$$anon$1.applyOrElse(LDPStore.scala:25)
    akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
    akka.actor.ActorCell.invoke(ActorCell.scala:456)
    akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
    akka.dispatch.Mailbox.run(Mailbox.scala:219)
    akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

In this code: rww.ldp.auth.WACAuthZ#acl

It seems the `futureACL: Future[Option[LinkedDataResource[Rdf]]]` variable receives in fact a `Some(Success(ScalaIOException))`

This is strange because in runLocalCmd we have:

```
        getResource(localName(uri)) match {
          case Success(res) => rwwRouterActor.tell(Scrpt(k(res)),context.sender)
          case Failure(fail) =>  context.sender ! fail
        }
```

And it seems to do `context.sender ! fail`

It should be nice to have a better error in these cases

**Comment by slorber** [comment]
The problem is because we have: `context.sender ! fail`

On the client side, the Future will be a Future[Exception] instead of being a Future[T], because the returned exception is considered as a normal result, which produces later the ClassCastException.

On this link:
http://doc.akka.io/docs/akka/snapshot/scala/actors.html

It is said:

```
Warning
To complete the future with an exception you need send a Failure message to the sender. This is not done automatically when an actor throws an exception while processing a message.
```

So we need to use this special syntax:
`context.sender ! akka.actor.Status.Failure(fail)`

We need to refactor existing code to remove all the places where errors were not properly handled.
