### ISSUE TITLE
Timeout problem when using uppercases in subdomain name

### ISSUE THREAD

**Issue by slorber** [read-write-web/rww-play#64]
I created a subdomain with an uppercase letter and it seems to produce problems.

It seems the chrome behavior is to convert the domain/subdomain all to lowercase before sending the request, probably because it is case insensitive and some kind of convention.

The effect is that I get a timeout when trying to access subdomain created with string "testSeb4" by using https://testseb4.localhost:8443/

```
Timed out
akka.pattern.AskTimeoutException: Timed out
    at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
    at akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)
    at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:691)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:688)
    at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)
    at akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)
    at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)
    at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
    at java.lang.Thread.run(Thread.java:744)
```

I think the easiest way is to forbid or convert the uppercase letters in the subdomain name.

I already saw this kind of timeout and it seems that it happens when we try to fetch a file/folder which doesn't exist on the filesystem, so I guess this timeout problem is a more general problem

**Comment by bblfish** [comment]
yes, we should open a timeout bug. That's going to be more difficult to fix in this version I think.
But yes, all domain names should be lowercased.

**Comment by bblfish** [comment]
One simple solution to this bug is that the subdomain name router needs to lowercase all domain names before sending the message out. This is OK because domains names are case insensitive.

**Comment by bblfish** [comment]
could not quite test the above. But it lowercases domain names on creation and on http request .
