### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by letnotimitateothers** [read-write-web/rww-play#80]
The rww-play server stops running by himself and I get the following logs : 

This first error happens periodically.
The second error is the final one in my terminal.

---

---

---

FIRST : 
[error] application -

! @6h2g5ogej - Internal server error, for (GET) [/srv/cors?url=https%3A%2F%2Fwww.bergnet.org%2Fpeople%2Fbergi%2Fcard] ->

play.api.Application$$anon$1: Execution exception[[ParserException: had problems parsing document returned by server]]
    at play.api.Application$class.handleError(Application.scala:296) ~[play_2.10.jar:2.2-TLS]
    at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.10.jar:2.2-TLS]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:237) [play_2.10.jar:2.2-TLS]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$13$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:234) [play_2.10.jar:2.2-TLS]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
Caused by: rww.ldp.ParserException: had problems parsing document returned by server
    at rww.ldp.WSClient$$anonfun$fetch$1.apply(WebClient.scala:100) ~[na:na]
    at rww.ldp.WSClient$$anonfun$fetch$1.apply(WebClient.scala:82) ~[na:na]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[scala-library.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library.jar:na]
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [akka-actor_2.10.jar:2.2.0]
Caused by: scalax.io.ScalaIOException: MainException: class org.openrdf.rio.RDFParseException(Illegal character in path at index 40: http://dbpedia.org/resource/Forrest_Gump" [line 50, column 77])
    at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:732) ~[sesame-rio-api-2.7.0.jar:na]
    at org.openrdf.rio.rdfxml.RDFXMLParser.reportFatalError(RDFXMLParser.java:1274) ~[sesame-rio-rdfxml-2.7.0.jar:na]
    at org.openrdf.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:377) ~[sesame-rio-rdfxml-2.7.0.jar:na]
    at org.openrdf.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:268) ~[sesame-rio-rdfxml-2.7.0.jar:na]
    at org.w3.banana.plantain.PlantainRDFXMLReader$$anonfun$read$2$$anonfun$apply$2.apply(PlantainRDFReader.scala:52) ~[plantain_2.10-2013_10_07-SNAPSHOT.jar:2013_10_07-SNAPSHOT]
    at org.w3.banana.plantain.PlantainRDFXMLReader$$anonfun$read$2$$anonfun$apply$2.apply(PlantainRDFReader.scala:48) ~[plantain_2.10-2013_10_07-SNAPSHOT.jar:2013_10_07-SNAPSHOT]
Caused by: org.openrdf.rio.RDFParseException: Illegal character in path at index 40: http://dbpedia.org/resource/Forrest_Gump" [line 50, column 77]
    at org.openrdf.rio.helpers.RDFParserBase.reportFatalError(RDFParserBase.java:732) ~[sesame-rio-api-2.7.0.jar:na]
    at org.openrdf.rio.rdfxml.RDFXMLParser.reportFatalError(RDFXMLParser.java:1274) ~[sesame-rio-rdfxml-2.7.0.jar:na]
    at org.openrdf.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:377) ~[sesame-rio-rdfxml-2.7.0.jar:na]
    at org.openrdf.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:268) ~[sesame-rio-rdfxml-2.7.0.jar:na]
    at org.w3.banana.plantain.PlantainRDFXMLReader$$anonfun$read$2$$anonfun$apply$2.apply(PlantainRDFReader.scala:52) ~[plantain_2.10-2013_10_07-SNAPSHOT.jar:2013_10_07-SNAPSHOT]
    at org.w3.banana.plantain.PlantainRDFXMLReader$$anonfun$read$2$$anonfun$apply$2.apply(PlantainRDFReader.scala:48) ~[plantain_2.10-2013_10_07-SNAPSHOT.jar:2013_10_07-SNAPSHOT]
Caused by: java.net.URISyntaxException: Illegal character in path at index 40: http://dbpedia.org/resource/Forrest_Gump"
    at java.net.URI$Parser.fail(URI.java:2829) ~[na:1.7.0_21]
    at java.net.URI$Parser.checkChars(URI.java:3002) ~[na:1.7.0_21]
    at java.net.URI$Parser.parseHierarchical(URI.java:3086) ~[na:1.7.0_21]
    at java.net.URI$Parser.parse(URI.java:3034) ~[na:1.7.0_21]
    at java.net.URI.<init>(URI.java:595) ~[na:1.7.0_21]
    at org.w3.banana.plantain.model.URI$.fromString(model.scala:268) ~[plantain_2.10-2013_10_07-SNAPSHOT.jar:2013_10_07-SNAPSHOT]
Uncaught error from thread [MySystem-akka.actor.default-dispatcher-8] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[MySystem]
Uncaught error from thread [MySystem-scheduler-1] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[MySystem]
[ERROR] [01/21/2014 15:34:31.694] [MySystem-scheduler-1] [ActorSystem(MySystem)] exception on LARS’ timer thread
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at akka.dispatch.AbstractNodeQueue.<init>(AbstractNodeQueue.java:19)
    at akka.actor.LightArrayRevolverScheduler$TaskQueue.<init>(Scheduler.scala:431)
    at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:397)
    at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
    at java.lang.Thread.run(Thread.java:722)

SECOND : 
ERROR] [01/21/2014 15:35:41.939] [MySystem-akka.actor.default-dispatcher-8] [ActorSystem(MySystem)] Uncaught error from thread [MySystem-akka.actor.default-dispatcher-8] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.regex.Matcher.<init>(Matcher.java:224)
    at java.util.regex.Pattern.matcher(Pattern.java:1088)
    at scala.util.matching.Regex.findPrefixMatchOf(Regex.scala:283)
    at scala.util.parsing.combinator.RegexParsers$class.handleWhiteSpace(RegexParsers.scala:75)
    at rww.ldp.LinkHeaderParser.handleWhiteSpace(LinkHeaderParser.scala:12)
    at scala.util.parsing.combinator.RegexParsers$$anon$2.apply(RegexParsers.scala:108)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.applyp$1(Parsers.scala:727)
    at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.continue$1(Parsers.scala:733)
    at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.apply(Parsers.scala:737)
    at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.apply(Parsers.scala:721)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Succesjava.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.regex.Matcher.<init>(Matcher.java:224)
    at java.util.regex.Pattern.matcher(Pattern.java:1088)
    at scala.util.matching.Regex.findPrefixMatchOf(Regex.scala:283)
    at scala.util.parsing.combinator.RegexParsers$class.handleWhiteSpace(RegexParsers.scala:75)
    at rww.ldp.LinkHeaderParser.handleWhiteSpace(LinkHeaderParser.scala:12)
    at scala.util.parsing.combinator.RegexParsers$$anon$2.apply(RegexParsers.scala:108)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.applyp$1(Parsers.scala:727)
    at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.continue$1(Parsers.scala:733)
    at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.apply(Parsers.scala:737)
    at scala.util.parsing.combinator.Parsers$$anonfun$rep1$1.apply(Parsers.flatMapWithNext(Parsers.scala:142)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)

s.scala:721)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$append$1.apply(Parsers.scala:254)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Success.flatMapWithNext(Parsers.scala:142)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$flatMap$1.apply(Parsers.scala:239)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
    at scala.util.parsing.combinator.Parsers$$anon$3.apply(Parsers.scala:222)
    at scala.util.parsing.combinator.Parsers$Parser$$anonfun$map$1.apply(Parsers.scala:242)
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at akka.dispatch.AbstractNodeQueue.<init>(AbstractNodeQueue.java:19)
    at akka.actor.LightArrayRevolverScheduler$TaskQueue.<init>(Scheduler.scala:431)
    at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:397)
[INFO] [01/21/2014 15:34:31.694] [MySystem-scheduler-1] [ActorSystem(MySystem)] starting new LARS thread
    at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
    at java.lang.Thread.run(Thread.java:722)
[ERROR] [01/21/2014 15:35:42.367] [MySystem-scheduler-1] [ActorSystem(MySystem)] Uncaught error from thread [MySystem-scheduler-1] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at akka.dispatch.AbstractNodeQueue.<init>(AbstractNodeQueue.java:19)
    at akka.actor.LightArrayRevolverScheduler$TaskQueue.<init>(Scheduler.scala:431)
    at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:397)
    at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
    at java.lang.Thread.run(Thread.java:722)

![capture decran 2014-01-21 a 15 43 50](https://f.cloud.github.com/assets/2323982/1964279/f3d9ac14-82aa-11e3-81f7-4265d9fed9d7.png)

**Comment by slorber** [comment]
This OOM was a previous bug already fixed. @letnotimitateothers was on a wrong branch
