### ISSUE TITLE
Editing card when on webdomain not working

### ISSUE THREAD

**Issue by letnotimitateothers** [read-write-web/rww-play#89]
I've got the error when I try to edit my profile when I'm on my subdomain (i.e. https://amelie.localhost:8443/card).

``` scala
Could not authenticate user with TLS cert:rww.ldp.auth.WebIDVerificationFailure
    at rww.ldp.auth.WebIDVerifier$$anonfun$verifyWebID$1$$anonfun$5.apply(WebIDVerifier.scala:159)
    at rww.ldp.auth.WebIDVerifier$$anonfun$verifyWebID$1$$anonfun$5.apply(WebIDVerifier.scala:150)
    at scala.Option.getOrElse(Option.scala:120)
    at rww.ldp.auth.WebIDVerifier$$anonfun$verifyWebID$1.apply(WebIDVerifier.scala:150)
    at rww.ldp.auth.WebIDVerifier$$anonfun$verifyWebID$1.apply(WebIDVerifier.scala:137)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by bblfish** [comment]
The issue arises because the WebID Certificate created in the  account creation for the subdomain is not the right one, as shown here:

![screen shot 2014-02-06 at 13 22 09](https://f.cloud.github.com/assets/124506/2124895/c37bc712-9247-11e3-835a-72119285c1b7.png)

This should be an easy thing to fix for Sebastien.

**Comment by slorber** [comment]
this has been fixed now we can edit
